deployment:
  annotations:
  labels: 
    app: rutube-backend
  name: rutube-backend-deployment
  replicaCount: 2
  pod:
    image:
      repository: localhost:5000/rutube-backend
      tag: latest
      pullPolicy: Always
    annotations: null
    resources: null
    name: rutube-backend-pod
      # limits:
      #   cpu:
      #   memory:
      # requests:
      #   cpu:
      #   memory:
service:
  name: rutube-backend-service
  containerPort: 80
  port: 80
  type: NodePort

configmap:
  name: rutube-backend-configmap
  values:
    MODEL_API_BASE_URL: 'http://rutube-model-service'
    
ingress:
  name: rutube-backend-ingress
  
