apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutube-backend
  labels:
    {{- toYaml .Values.labels | nindent 8 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 8 }}
  template:
    metadata:
      {{- if .Values.pod.annotations }}
      annotations:
        {{- toYaml .Values.pod.annotations | nindent 8 }}
      {{- end}}
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
        - name: rutube-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end}}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              name: fastapi-port