{{- with .Values.ingress}}
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: {{ .name }}
{{- end }}
spec:
  {{- with .Values.service }}
  rules:
    - host: bot-backend.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
  defaultBackend:
    service:
      name: {{ .name }}
      port:
        number: {{ .port }}
{{- end }}
