{{- with .Values.ingress}}
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: {{ .name }}
{{- end }}
spec:
  {{- with .Values.service }}
  defaultBackend:
    service:
      name: {{ .name }}
      port:
        number: {{ .port }}
{{- end }}
