apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "example-ingress"
spec:
  defaultBackend:
    service:
      name: {{ .Values.name }}-service
      port:
        number: {{ .Values.service.port }}
